name: python-hello-world-with-unit-test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pipenv coverage flask pytest
    - name: Analysing the code with test
      run: |
        chmod +x nix/run_tests_and_coverage.sh
        sh nix/run_tests_and_coverage.sh
        ls 
       # pylint $(git ls-files '*.py')
    - name: Export Workflow Trace
      if: always()
      uses: inception-health/otel-export-trace-action@latest
      with:
        otlpEndpoint: https://otlp.eu01.nr-data.net
        otlpHeaders: ${{ secrets.OTLP_HEADERS }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        runId: ${{ github.event.workflow_run.id }}
