name: python-hello-world-with-unit-test

on: 
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pipenv coverage flask pytest
    - name: Analysing-the-code-with-test
      run: |
       #!/usr/bin/env sh
        pipenv run coverage run -m unittest discover -b
        pipenv run coverage report -m  --include="src/*" --omit="*/test/*,src/__init__*"
        pipenv run coverage xml -o test/coverage.xml
        pipenv run pytest ./test/  --junitxml=test/test_summary.xml -o junit_family=xunit2
#     - name: Post JUnit test results to New Relic
#       uses: newrelic/junit-reporter-action@v0.1.1
#       with:
#           accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
#           ingestLicenseKey: ${{ secrets.NEW_RELIC_INGEST_LICENSE_KEY }}
#           testOutputPath: test/test_summary.xml
    - uses: inception-health/otel-upload-test-artifact-action@latest
      if: always()
      with:
        jobName: "run-test"
        stepName: "Analysing-the-code-with-test"
        path: "test/test_summary.xml"
        type: "junit"
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Export Workflow Trace
      if: always()
      uses: inception-health/otel-export-trace-action@latest
      with:
        otlpEndpoint: https://otlp.eu01.nr-data.net
        otlpHeaders: ${{ secrets.OTLP_HEADERS }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        runId: ${{ github.event.workflow_run.id }}
    - name: Sends New Relic test metric
      id: newrelic-metric
      uses: barecheck/newrelic-metric-action@v0.2-beta.1
      with:
        insertApiKey: ${{ secrets.NEW_RELIC_INSERT_API_KEY }}
        accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        region: EU
        application: "python-hello-world-with-unit-test"
        metricName: "testMetric"
        metricValue: 45.6
