name: python-hello-world-with-unit-test

on: 
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pipenv coverage flask pytest
    - name: Analysing-the-code-with-test
      run: |
       #!/usr/bin/env sh
        pipenv run coverage run -m unittest discover -b
        pipenv run coverage report -m  --include="src/*" --omit="*/test/*,src/__init__*"
        pipenv run coverage xml
        pipenv run pytest ./test/  --junitxml=test_summary.xml -o junit_family=xunit2
  
    - uses: inception-health/otel-upload-test-artifact-action@latest
      if: always()
      with:
        jobName: "run-test (${{ matrix.python-version }})"
        stepName: "Analysing-the-code-with-test"
        path: "test_summary.xml"
        type: "junit"
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Export Workflow Trace
      if: always()
      uses: inception-health/otel-export-trace-action@latest
      with:
        otlpEndpoint: https://otlp.eu01.nr-data.net
        otlpHeaders: ${{ secrets.OTLP_HEADERS }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        runId: ${{ github.event.workflow_run.id }}
